package core.domain.sales.model;

import common.util.*;
import core.domain.api.model.Record;

/**
 * Represents the accumulated sales data for a specific product.
 *
 * Each instance keeps track of:
 * - Basic product details (ID, name, price, stock)
 * - Total sales revenue generated by the product
 * - Total number of items sold
 *
 * This class is part of the domain layer and acts as a summary record
 * that updates whenever a sale is recorded.
 */
public class ProductTotals implements Record {
    private final String id;
    private String name;
    private double price;
    private int stock;
    private double totalSales;
    private int totalStockSold;

    public ProductTotals(String id,
                         String name,
                         double price,
                         int stock) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.stock = stock;
        totalSales = 0;
        totalStockSold = 0;
    }

    // GETTERS
    public String getId() {return id;}
    public String getName() {return name;}
    public double getPrice() {return price;}
    public int getStock() {return stock;}
    public double getTotalSales() {return totalSales;}
    public int getTotalStockSold() {return totalStockSold;}

    // SETTERS
    public void setName(String name){this.name=name;}
    public void setPrice(double price){this.price=price;}
    public void setStock(int stock){this.stock=stock;}

    // MUTATORS
    public void recordPurchase(int stockSold){
        if(stockSold<1) throw new IllegalArgumentException("Stock sold must at least be 1");
        totalSales += price * stockSold;
        totalStockSold += stockSold;
        stock-=stockSold;
    }

    @Override
    public String toString() {
        return String.format("%n%s %-9s %s| %-20s | %-10.2f | %-5d | %-11.2f | %-5d%n",
                Ansi.Color.DIM_WHITE.code() + Ansi.Format.REVERSE.code(),
                id,
                Ansi.Format.RESET.code(),
                name,
                price,
                stock,
                totalSales,
                totalStockSold);
    }
}
